name: Build

on:
  push:
    branches: [ Assignment* ]
  pull_request:
    branches: [ Assignment* ]

jobs:
  build:
  
    defaults:
      run:
        working-directory: ./SecretSanta/
        
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
      
    - name: Npm Build
      working-directory: ./SecretSanta/src/SecretSanta.Web/
      run: |
        npm install
        npm run build:prod
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Test
      run: dotnet test --no-build --verbosity normal
      